import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='min-h-screen flex flex-col justify-between space-y-8'>
          <Navbar />
          <div className="max-w-7xl h-full mx-auto">
            {children}
          </div>
          <Footer />
        </div>  
      </body>
      
    </html>
  )
}
